// scripts/pageData.ts
export const pages = [
  {
    _id: 'page-red-shoes',
    _type: 'page',
    title: 'Red Shoes',
    slug: { current: 'red-shoes' },
    body: 'Comfortable red shoes for running.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Buy red running shoes online.',
    category: 'Footwear',
  },
  {
    _id: 'page-blue-shirt',
    _type: 'page',
    title: 'Blue Shirt',
    slug: { current: 'blue-shirt' },
    body: 'Stylish blue shirt for casual wear.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Shop trendy blue shirts.',
    category: 'Clothing',
  },
  {
    _id: 'page-green-hat',
    _type: 'page',
    title: 'Green Hat',
    slug: { current: 'green-hat' },
    body: 'A cool green hat for sunny days.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Find fashionable green hats.',
    category: 'Accessories',
  },
  {
    _id: 'page-black-jacket',
    _type: 'page',
    title: 'Black Jacket',
    slug: { current: 'black-jacket' },
    body: 'Warm black jacket for winter.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Stay cozy with black jackets.',
    category: 'Clothing',
  },
  {
    _id: 'page-white-sneakers',
    _type: 'page',
    title: 'White Sneakers',
    slug: { current: 'white-sneakers' },
    body: 'Classic white sneakers for everyday wear.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Timeless white sneakers available.',
    category: 'Footwear',
  },
  {
    _id: 'page-yellow-scarf',
    _type: 'page',
    title: 'Yellow Scarf',
    slug: { current: 'yellow-scarf' },
    body: 'Bright yellow scarf for chilly days.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Add color with yellow scarves.',
    category: 'Accessories',
  },
  {
    _id: 'page-purple-dress',
    _type: 'page',
    title: 'Purple Dress',
    slug: { current: 'purple-dress' },
    body: 'Elegant purple dress for evening wear.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Shop elegant purple dresses.',
    category: 'Clothing',
  },
  {
    _id: 'page-orange-shorts',
    _type: 'page',
    title: 'Orange Shorts',
    slug: { current: 'orange-shorts' },
    body: 'Comfortable orange shorts for summer.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Perfect shorts for hot days.',
    category: 'Clothing',
  },
  {
    _id: 'page-brown-belt',
    _type: 'page',
    title: 'Brown Belt',
    slug: { current: 'brown-belt' },
    body: 'Durable brown leather belt.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Classic brown belts in stock.',
    category: 'Accessories',
  },
  {
    _id: 'page-grey-hoodie',
    _type: 'page',
    title: 'Grey Hoodie',
    slug: { current: 'grey-hoodie' },
    body: 'Casual grey hoodie for everyday comfort.',
    image_url: 'https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0',
    seo_description: 'Stay casual with grey hoodies.',
    category: 'Clothing',
  },
]
